version: "3"
services:
 python_service:
   build:
     context: ./
     dockerfile: Dockerfile
   image: w1
   container_name: w1_python_container
   stdin_open: true #  docker attach container_id
   tty: true
   ports:
    - "5000:5000"
   volumes:
    - .:/app
 psql-db:
  image: 'postgres:14'
  container_name: psql-db
  environment:
    - PGPASSWORD=123456
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123456
  ports:
    - '5434:5432'
